# Promote releases to main when a "release PR" is merged into `next`. This will
# subsequently kick off the publish workflow.
name: Promotion
on:
  pull_request:
    types:
      - closed
    branches:
      - next

permissions:
  contents: write
  packages: write

jobs:
  promote:
    # Only run when we've merged a "Release PR" into `next`. Prevents a full
    # release from happening when we're merging codegen changes into `next`
    # prior to the release approval process.
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release-please--branches--next')
    runs-on: ubuntu-latest
    steps:
      - name: release app token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.SDK_RELEASE_APP_ID }}
          private-key: ${{ secrets.SDK_RELEASE_PRIVATE_KEY }}
          owner: keycardai
          repositories: |
            keycard-python

      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: configure author
        run: |
          APP_NAME="keycard-sdk-release[bot]"
          APP_ID="${{ vars.SDK_RELEASE_APP_ID }}"
          git config --global user.name "$APP_NAME"
          git config --global user.email "$APP_ID+$APP_NAME@users.noreply.github.com"

      - name: fast foward next → main
        run: |
          git fetch origin main:main
          git fetch origin next:next

          if ! git merge-base --is-ancestor main next; then
            echo "❌ Error: 'next' has diverged from 'main'. A fast-foward is not possible."
            exit 1
          fi

          git checkout main
          git merge next --ff-only
          git push origin main
          echo "✅ Promoted 'next' to 'main'"
